import { MigrationInterface, QueryRunner } from 'typeorm';

export class Heroes1764452446167 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE heroes (
    id        INTEGER PRIMARY KEY,
    name      TEXT NOT NULL UNIQUE,
    attribute SMALLINT NOT NULL,
    melee     BOOLEAN NOT NULL
);
`)
        await queryRunner.query(`
        INSERT INTO heroes(id, name, attribute, melee)
VALUES(1, 'npc_dota_hero_antimage', 1, TRUE),
      (2, 'npc_dota_hero_axe', 0, TRUE),
      (3, 'npc_dota_hero_bane', 3, FALSE),
      (4, 'npc_dota_hero_bloodseeker', 1, TRUE),
      (5, 'npc_dota_hero_crystal_maiden', 2, FALSE),
      (6, 'npc_dota_hero_drow_ranger', 1, FALSE),
      (7, 'npc_dota_hero_earthshaker', 0, TRUE),
      (8, 'npc_dota_hero_juggernaut', 1, TRUE),
      (9, 'npc_dota_hero_mirana', 1, FALSE),
      (10, 'npc_dota_hero_morphling', 1, FALSE),
      (11, 'npc_dota_hero_nevermore', 1, FALSE),
      (12, 'npc_dota_hero_phantom_lancer', 1, FALSE),
      (13, 'npc_dota_hero_puck', 2, FALSE),
      (14, 'npc_dota_hero_pudge', 0, FALSE),
      (15, 'npc_dota_hero_razor', 1, FALSE),
      (16, 'npc_dota_hero_sand_king', 3, TRUE),
      (17, 'npc_dota_hero_storm_spirit', 2, FALSE),
      (18, 'npc_dota_hero_sven', 0, TRUE),
      (19, 'npc_dota_hero_tiny', 0, TRUE),
      (20, 'npc_dota_hero_vengefulspirit', 1, FALSE),
      (21, 'npc_dota_hero_windrunner', 3, FALSE),
      (22, 'npc_dota_hero_zuus', 2, FALSE),
      (23, 'npc_dota_hero_kunkka', 0, TRUE),
      (25, 'npc_dota_hero_lina', 2, FALSE),
      (26, 'npc_dota_hero_lion', 2, FALSE),
      (27, 'npc_dota_hero_shadow_shaman', 2, FALSE),
      (28, 'npc_dota_hero_slardar', 0, TRUE),
      (29, 'npc_dota_hero_tidehunter', 0, TRUE),
      (30, 'npc_dota_hero_witch_doctor', 2, FALSE),
      (31, 'npc_dota_hero_lich', 2, FALSE),
      (32, 'npc_dota_hero_riki', 1, TRUE),
      (33, 'npc_dota_hero_enigma', 3, FALSE),
      (34, 'npc_dota_hero_tinker', 2, FALSE),
      (35, 'npc_dota_hero_sniper', 1, FALSE),
      (36, 'npc_dota_hero_necrolyte', 2, FALSE),
      (37, 'npc_dota_hero_warlock', 2, FALSE),
      (38, 'npc_dota_hero_beastmaster', 3, TRUE),
      (39, 'npc_dota_hero_queenofpain', 2, FALSE),
      (40, 'npc_dota_hero_venomancer', 3, FALSE),
      (41, 'npc_dota_hero_faceless_void', 1, TRUE),
      (42, 'npc_dota_hero_skeleton_king', 0, TRUE),
      (43, 'npc_dota_hero_death_prophet', 3, FALSE),
      (44, 'npc_dota_hero_phantom_assassin', 1, TRUE),
      (45, 'npc_dota_hero_pugna', 2, FALSE),
      (46, 'npc_dota_hero_templar_assassin', 1, FALSE),
      (47, 'npc_dota_hero_viper', 1, FALSE),
      (48, 'npc_dota_hero_luna', 1, FALSE),
      (49, 'npc_dota_hero_dragon_knight', 0, TRUE),
      (50, 'npc_dota_hero_dazzle', 3, FALSE),
      (51, 'npc_dota_hero_rattletrap', 0, TRUE),
      (52, 'npc_dota_hero_leshrac', 2, FALSE),
      (53, 'npc_dota_hero_furion', 3, FALSE),
      (54, 'npc_dota_hero_life_stealer', 0, TRUE),
      (55, 'npc_dota_hero_dark_seer', 2, TRUE),
      (56, 'npc_dota_hero_clinkz', 1, FALSE),
      (57, 'npc_dota_hero_omniknight', 0, TRUE),
      (58, 'npc_dota_hero_enchantress', 2, FALSE),
      (59, 'npc_dota_hero_huskar', 0, FALSE),
      (60, 'npc_dota_hero_night_stalker', 0, TRUE),
      (61, 'npc_dota_hero_broodmother', 1, FALSE),
      (62, 'npc_dota_hero_bounty_hunter', 1, TRUE),
      (63, 'npc_dota_hero_weaver', 1, FALSE),
      (64, 'npc_dota_hero_jakiro', 2, FALSE),
      (65, 'npc_dota_hero_batrider', 3, FALSE),
      (66, 'npc_dota_hero_chen', 2, FALSE),
      (67, 'npc_dota_hero_spectre', 3, TRUE),
      (68, 'npc_dota_hero_ancient_apparition', 2, FALSE),
      (69, 'npc_dota_hero_doom_bringer', 0, FALSE),
      (70, 'npc_dota_hero_ursa', 1, TRUE),
      (71, 'npc_dota_hero_spirit_breaker', 0, FALSE),
      (72, 'npc_dota_hero_gyrocopter', 1, FALSE),
      (73, 'npc_dota_hero_alchemist', 0, TRUE),
      (74, 'npc_dota_hero_invoker', 2, FALSE),
      (75, 'npc_dota_hero_silencer', 2, FALSE),
      (76, 'npc_dota_hero_obsidian_destroyer', 2, FALSE),
      (77, 'npc_dota_hero_lycan', 0, TRUE),
      (78, 'npc_dota_hero_brewmaster', 3, TRUE),
      (79, 'npc_dota_hero_shadow_demon', 2, FALSE),
      (80, 'npc_dota_hero_lone_druid', 1, FALSE),
      (81, 'npc_dota_hero_chaos_knight', 0, TRUE),
      (82, 'npc_dota_hero_meepo', 1, TRUE),
      (83, 'npc_dota_hero_treant', 0, TRUE),
      (84, 'npc_dota_hero_ogre_magi', 0, TRUE),
      (85, 'npc_dota_hero_undying', 0, TRUE),
      (86, 'npc_dota_hero_rubick', 2, FALSE),
      (87, 'npc_dota_hero_disruptor', 2, FALSE),
      (88, 'npc_dota_hero_nyx_assassin', 3, TRUE),
      (89, 'npc_dota_hero_naga_siren', 1, TRUE),
      (90, 'npc_dota_hero_keeper_of_the_light', 2, FALSE),
      (91, 'npc_dota_hero_wisp', 3, FALSE),
      (92, 'npc_dota_hero_visage', 3, FALSE),
      (93, 'npc_dota_hero_slark', 1, TRUE),
      (94, 'npc_dota_hero_medusa', 1, FALSE),
      (95, 'npc_dota_hero_troll_warlord', 1, FALSE),
      (96, 'npc_dota_hero_centaur', 0, TRUE),
      (97, 'npc_dota_hero_magnataur', 3, FALSE),
      (98, 'npc_dota_hero_shredder', 0, TRUE),
      (99, 'npc_dota_hero_bristleback', 0, TRUE),
      (100, 'npc_dota_hero_tusk', 0, TRUE),
      (101, 'npc_dota_hero_skywrath_mage', 2, FALSE),
      (102, 'npc_dota_hero_abaddon', 3, TRUE),
      (103, 'npc_dota_hero_elder_titan', 0, TRUE),
      (104, 'npc_dota_hero_legion_commander', 0, TRUE),
      (105, 'npc_dota_hero_techies', 3, FALSE),
      (106, 'npc_dota_hero_ember_spirit', 1, TRUE),
      (107, 'npc_dota_hero_earth_spirit', 0, TRUE),
      (108, 'npc_dota_hero_abyssal_underlord', 0, FALSE),
      (109, 'npc_dota_hero_terrorblade', 1, TRUE),
      (110, 'npc_dota_hero_phoenix', 0, FALSE),
      (111, 'npc_dota_hero_oracle', 2, FALSE),
      (112, 'npc_dota_hero_winter_wyvern', 2, FALSE)
        `)
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
    }

}
