/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import { ForumThreadType, ForumThreadTypeFromJSON, ForumThreadTypeFromJSONTyped, ForumThreadTypeToJSON } from './';

/**
 *
 * @export
 * @interface ForumCreateThreadDTO
 */
export class ForumCreateThreadDTO {
    /**
     *
     * @type {ForumThreadType}
     * @memberof ForumCreateThreadDTO
     */
    threadType: ForumThreadType;
    /**
     *
     * @type {string}
     * @memberof ForumCreateThreadDTO
     */
    externalId: string;
    /**
     *
     * @type {string}
     * @memberof ForumCreateThreadDTO
     */
    title: string;
    /**
     *
     * @type {string}
     * @memberof ForumCreateThreadDTO
     */
    op?: string;
}

export function ForumCreateThreadDTOFromJSON(json: any): ForumCreateThreadDTO {
    return ForumCreateThreadDTOFromJSONTyped(json, false);
}

export function ForumCreateThreadDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForumCreateThreadDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'threadType': ForumThreadTypeFromJSON(json['threadType']),
        'externalId': json['externalId'],
        'title': json['title'],
        'op': !exists(json, 'op') ? undefined : json['op'],
    };
}

export function ForumCreateThreadDTOToJSON(value?: ForumCreateThreadDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'threadType': ForumThreadTypeToJSON(value.threadType),
        'externalId': value.externalId,
        'title': value.title,
        'op': value.op,
    };
}


