/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import { ForumJwtPayload, ForumJwtPayloadFromJSON, ForumJwtPayloadToJSON } from './';

/**
 *
 * @export
 * @interface ForumCreateMessageDTO
 */
export class ForumCreateMessageDTO {
    /**
     *
     * @type {ForumJwtPayload}
     * @memberof ForumCreateMessageDTO
     */
    author: ForumJwtPayload;
    /**
     *
     * @type {string}
     * @memberof ForumCreateMessageDTO
     */
    content: string;
    /**
     *
     * @type {string}
     * @memberof ForumCreateMessageDTO
     */
    replyMessageId?: string;
}

export function ForumCreateMessageDTOFromJSON(json: any): ForumCreateMessageDTO {
    return ForumCreateMessageDTOFromJSONTyped(json, false);
}

export function ForumCreateMessageDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForumCreateMessageDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'author': ForumJwtPayloadFromJSON(json['author']),
        'content': json['content'],
        'replyMessageId': !exists(json, 'replyMessageId') ? undefined : json['replyMessageId'],
    };
}

export function ForumCreateMessageDTOToJSON(value?: ForumCreateMessageDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'author': ForumJwtPayloadToJSON(value.author),
        'content': value.content,
        'replyMessageId': value.replyMessageId,
    };
}


