/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ForumEmoticonDto
 */
export class ForumEmoticonDto {
    /**
     *
     * @type {number}
     * @memberof ForumEmoticonDto
     */
    id: number;
    /**
     *
     * @type {string}
     * @memberof ForumEmoticonDto
     */
    code: string;
    /**
     *
     * @type {string}
     * @memberof ForumEmoticonDto
     */
    bucket: string;
    /**
     *
     * @type {string}
     * @memberof ForumEmoticonDto
     */
    key: string;
}

export function ForumEmoticonDtoFromJSON(json: any): ForumEmoticonDto {
    return ForumEmoticonDtoFromJSONTyped(json, false);
}

export function ForumEmoticonDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForumEmoticonDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'id': json['id'],
        'code': json['code'],
        'bucket': json['bucket'],
        'key': json['key'],
    };
}

export function ForumEmoticonDtoToJSON(value?: ForumEmoticonDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'id': value.id,
        'code': value.code,
        'bucket': value.bucket,
        'key': value.key,
    };
}


