/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ForumThreadDTO, ForumThreadDTOFromJSON, ForumThreadDTOToJSON } from './';

/**
 *
 * @export
 * @interface ForumThreadPageDto
 */
export class ForumThreadPageDto {
    /**
     *
     * @type {Array<ForumThreadDTO>}
     * @memberof ForumThreadPageDto
     */
    data: Array<ForumThreadDTO>;
    /**
     *
     * @type {number}
     * @memberof ForumThreadPageDto
     */
    perPage: number;
    /**
     *
     * @type {number}
     * @memberof ForumThreadPageDto
     */
    page: number;
    /**
     *
     * @type {number}
     * @memberof ForumThreadPageDto
     */
    pages: number;
}

export function ForumThreadPageDtoFromJSON(json: any): ForumThreadPageDto {
    return ForumThreadPageDtoFromJSONTyped(json, false);
}

export function ForumThreadPageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForumThreadPageDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'data': ((json['data'] as Array<any>).map(ForumThreadDTOFromJSON)),
        'perPage': json['perPage'],
        'page': json['page'],
        'pages': json['pages'],
    };
}

export function ForumThreadPageDtoToJSON(value?: ForumThreadPageDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'data': ((value.data as Array<any>).map(ForumThreadDTOToJSON)),
        'perPage': value.perPage,
        'page': value.page,
        'pages': value.pages,
    };
}


