/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ForumUpdateMessageReactionDto
 */
export class ForumUpdateMessageReactionDto {
    /**
     *
     * @type {string}
     * @memberof ForumUpdateMessageReactionDto
     */
    author: string;
    /**
     *
     * @type {number}
     * @memberof ForumUpdateMessageReactionDto
     */
    emoticonId: number;
}

export function ForumUpdateMessageReactionDtoFromJSON(json: any): ForumUpdateMessageReactionDto {
    return ForumUpdateMessageReactionDtoFromJSONTyped(json, false);
}

export function ForumUpdateMessageReactionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForumUpdateMessageReactionDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'author': json['author'],
        'emoticonId': json['emoticonId'],
    };
}

export function ForumUpdateMessageReactionDtoToJSON(value?: ForumUpdateMessageReactionDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'author': value.author,
        'emoticonId': value.emoticonId,
    };
}


