/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ForumUpdateUserDTO
 */
export class ForumUpdateUserDTO {
    /**
     *
     * @type {string}
     * @memberof ForumUpdateUserDTO
     */
    muteUntil: string;
}

export function ForumUpdateUserDTOFromJSON(json: any): ForumUpdateUserDTO {
    return ForumUpdateUserDTOFromJSONTyped(json, false);
}

export function ForumUpdateUserDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForumUpdateUserDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'muteUntil': json['muteUntil'],
    };
}

export function ForumUpdateUserDTOToJSON(value?: ForumUpdateUserDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'muteUntil': value.muteUntil,
    };
}


