/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ForumEmoticonDto, ForumEmoticonDtoFromJSON, ForumEmoticonDtoToJSON } from './';

/**
 *
 * @export
 * @interface ForumReactionEntry
 */
export class ForumReactionEntry {
    /**
     *
     * @type {ForumEmoticonDto}
     * @memberof ForumReactionEntry
     */
    emoticon: ForumEmoticonDto;
    /**
     *
     * @type {Array<string>}
     * @memberof ForumReactionEntry
     */
    reacted: Array<string>;
}

export function ForumReactionEntryFromJSON(json: any): ForumReactionEntry {
    return ForumReactionEntryFromJSONTyped(json, false);
}

export function ForumReactionEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForumReactionEntry {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'emoticon': ForumEmoticonDtoFromJSON(json['emoticon']),
        'reacted': json['reacted'],
    };
}

export function ForumReactionEntryToJSON(value?: ForumReactionEntry | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'emoticon': ForumEmoticonDtoToJSON(value.emoticon),
        'reacted': value.reacted,
    };
}


