/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ForumJwtPayload, ForumJwtPayloadFromJSON, ForumJwtPayloadToJSON } from './';

/**
 *
 * @export
 * @interface ForumEditMessageDTO
 */
export class ForumEditMessageDTO {
    /**
     *
     * @type {ForumJwtPayload}
     * @memberof ForumEditMessageDTO
     */
    author: ForumJwtPayload;
    /**
     *
     * @type {string}
     * @memberof ForumEditMessageDTO
     */
    content: string;
}

export function ForumEditMessageDTOFromJSON(json: any): ForumEditMessageDTO {
    return ForumEditMessageDTOFromJSONTyped(json, false);
}

export function ForumEditMessageDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForumEditMessageDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'author': ForumJwtPayloadFromJSON(json['author']),
        'content': json['content'],
    };
}

export function ForumEditMessageDTOToJSON(value?: ForumEditMessageDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'author': ForumJwtPayloadToJSON(value.author),
        'content': value.content,
    };
}


