/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ForumRole, ForumRoleFromJSON, ForumRoleFromJSONTyped, ForumRoleToJSON } from './';

/**
 *
 * @export
 * @interface ForumJwtPayload
 */
export class ForumJwtPayload {
    /**
     *
     * @type {Array<ForumRole>}
     * @memberof ForumJwtPayload
     */
    roles: Array<ForumRole>;
    /**
     *
     * @type {string}
     * @memberof ForumJwtPayload
     */
    steam_id: string;
}

export function ForumJwtPayloadFromJSON(json: any): ForumJwtPayload {
    return ForumJwtPayloadFromJSONTyped(json, false);
}

export function ForumJwtPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForumJwtPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'roles': ((json['roles'] as Array<any>).map(ForumRoleFromJSON)),
        'steam_id': json['steam_id'],
    };
}

export function ForumJwtPayloadToJSON(value?: ForumJwtPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'roles': ((value.roles as Array<any>).map(ForumRoleToJSON)),
        'steam_id': value.steam_id,
    };
}


