/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ForumSortOrder {
    ASC = 'ASC',
    DESC = 'DESC'
}

export function ForumSortOrderFromJSON(json: any): ForumSortOrder {
    return ForumSortOrderFromJSONTyped(json, false);
}

export function ForumSortOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForumSortOrder {
    return json as ForumSortOrder;
}

export function ForumSortOrderToJSON(value?: ForumSortOrder | null): any {
    return value as any;
}

