/* tslint:disable */
/* eslint-disable */
/**
 * GameServer api
 * Matches, players, mmrs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ForumForumUserDTO
 */
export class ForumForumUserDTO {
    /**
     *
     * @type {string}
     * @memberof ForumForumUserDTO
     */
    steamId: string;
    /**
     *
     * @type {string}
     * @memberof ForumForumUserDTO
     */
    muteUntil: string;
    /**
     *
     * @type {number}
     * @memberof ForumForumUserDTO
     */
    messages: number;
}

export function ForumForumUserDTOFromJSON(json: any): ForumForumUserDTO {
    return ForumForumUserDTOFromJSONTyped(json, false);
}

export function ForumForumUserDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForumForumUserDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'steamId': json['steamId'],
        'muteUntil': json['muteUntil'],
        'messages': json['messages'],
    };
}

export function ForumForumUserDTOToJSON(value?: ForumForumUserDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'steamId': value.steamId,
        'muteUntil': value.muteUntil,
        'messages': value.messages,
    };
}


