/* tslint:disable */
/* eslint-disable */

/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Dota_GameMode } from '../../gateway/shared-types/dota-game-mode';

export type GameserverDotaGameMode = Dota_GameMode;

export function GameserverDotaGameModeFromJSON(
  json: any,
): GameserverDotaGameMode {
  return GameserverDotaGameModeFromJSONTyped(json, false);
}

export function GameserverDotaGameModeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GameserverDotaGameMode {
  return json as GameserverDotaGameMode;
}

export function GameserverDotaGameModeToJSON(
  value?: GameserverDotaGameMode | null,
): any {
  return value as any;
}
